feat: validate inputs

diff --git a/.github/workflows/create-patch-release-branch.yaml b/.github/workflows/create-patch-release-branch.yaml
--- a/.github/workflows/create-patch-release-branch.yaml
+++ b/.github/workflows/create-patch-release-branch.yaml
@@ -26,6 +26,21 @@ jobs:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
+      - name: Validate inputs
+        run: |
+          if ! [[ "${{ inputs.old_version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z]+(\.[0-9A-Za-z]+)*)?$ ]]; then
+            echo "Invalid old version format: ${{ inputs.old_version }}"
+            exit 1
+          fi
+          if ! [[ "${{ inputs.new_version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z]+(\.[0-9A-Za-z]+)*)?$ ]]; then
+            echo "Invalid new version format: ${{ inputs.new_version }}"
+            exit 1
+          fi
+      - name: Notify if inputs are invalid
+        if: {{ failure() }}
+        run: |
+          curl -X POST -H "Content-Type: application/json" -d '{"success": false, "message": "The old or new version you provided is invalid, make sure they both follow the SemVer format"}' ${{ inputs.resumeUrl }}
+          exit 1
       - name: Setup, cherry-pick and push branch
         run: |
           git config user.name "github-actions[bot]"
@@ -36,7 +51,7 @@ jobs:
           IFS=',' read -ra SHAS <<< "${{ inputs.commit_shas }}"
           for sha in "${SHAS[@]}"; do
             sha=$(echo $sha | xargs)
-            if ! git merge-base --is-ancestor $sha HEAD; then
+            if ! [[ git merge-base --is-ancestor $sha HEAD; ]] then
               echo "Cherry-picking commit $sha"
               git cherry-pick $sha
             else
